[package]
name = "combine-http"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
combine = "^3.0.0"
bencher = "0.1"

[profile.release]
lto = "fat"
codegen-units = 1
